### ISSUE TITLE
Feature Request: Slack channel notifications

### ISSUE THREAD

**Issue by timnovis** [rhyswfbowles/SeoCheck#3]
As a user I would like to be able to choose a Slack channel where any issues are posted automatically by the application

**Comment by rhyswfbowles** [comment]
This would make a great addition, unfortunately slackbots aren't my strongest suite so if anyone with that skillset would like to add this addition, it'd be greatly appreciated!

**Comment by timnovis** [comment]
If you like you can assign this to me and I will take it on

**Comment by timnovis** [comment]
This has been completed
